#---------------------------------------------------------------------------------------------
# Name: HabitatAssociations.R
# Purpose: THis script takes a list of species/habitat associations (generated by extract 
#          by values in ArcGIS) and compares these observed proportions to expected values 
#          (which in this case is the relative proportion of each habitat type in the project
#          area generated by a Tabulate Area command)
# Author: Christopher Tracey
# Created: 2016-02-12
# Updated: 2016-02-22
#
# Updates:
# insert date and info
# * 2016-02-22 - cleaned up the code and documentation
#
# To Do List/Future Ideas:
# * bootstrapping
# * compact the code up a little.
#---------------------------------------------------------------------------------------------

# load in the 'reshape' and 'data.table' packages
library(reshape)
library(data.table)

# reads the habitat proportions in
# data should be a csv file with the following format: 
# ES_NAME,area_meters,acres,proportion
habitat = read.csv("data_habitat.csv")
setnames(habitat,"proportion","expected") # this renames the 'proportion' field to 'expected'

# reads in the occurence data 
# data should be a csv file with the followign format:
# OBJECTID,EO_ID,ELCODE,EO_NUM,SNAME,SCOMNAME,ELSUBID,ID_CONFIRM,LASTOBS,SURVEYDATE,EORANK,GRANK,SRANK,USESA,SPROT,PBSSTATUS,PBSQUAL,SWG_STATUS,SWGCOM,EO_TYPE,SITE_NAME,SURVEYSITE,EO_TRACK,SENSITV_SP,SENSITV_EO,EO_DATA,GEN_DESC,EORANKCOM,MGMT_COM,GENERL_COM,PREC_BCD,EST_RA,QUAD_FILE,ER_RULE,X,Y,LEAD_RESP,MOD_BY,MOD_DATE,MAPPEDBY,MAPPEDDATE,EXPT_DATE,RASTERVALU,ES_NAME
# the only really important fields above are 'SNAME' and 'ES_NAME'
occur_missing = read.csv("MissingTerr.csv")

# I think any bootstrapping or subset selection needs to be placed around here

# turns the data frame into a table of counts and calculate proportions. 
# the margin setting in prop.table adds row summaries of the individual habitat proportions
count_table <- table(occur_missing$SNAME,occur_missing$ES_NAME) # turns the raw data into a table of counts
prop_table <- prop.table(count_table,margin=1) # adds column? summaries
prop_table <- addmargins(prop_table,margin=2) #adds row? summaries

# convert prop_table into a dataframe
occ_prop <- as.data.frame.matrix(prop_table) 
occ_prop <- cbind(row.names = rownames(occ_prop), occ_prop) # adds the row names into the data frame
setDT(occ_prop, keep.rownames = TRUE)[]

# this transforms the data into a table with one entry per species and habitat combination, this makes
#    the calculatations a little easier (eg. less matrix math)
results_melt <- melt(occ_prop, id="rn")
setnames(results_melt,"variable","ES_NAME") 
setnames(results_melt,"value","observed")
data_merge <- merge(results_melt,habitat,by="ES_NAME",all=TRUE)

#calculates th observed minus expected values
data_merge$minus <- (data_merge$observed - data_merge$expected)